
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  chat-service:
    build:
      context: ./chat-service-dotnet
      dockerfile: Dockerfile
    container_name: chat-service
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"

  auth-service:
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
    container_name: auth-service
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_URLS=http://+:5219
      - RabbitMq__HostName=rabbitmq
      - RabbitMq__UserName=guest
      - RabbitMq__Password=guest
      - RabbitMq__Port=5672
    ports:
      - "5219:5219"

  gift-wishlist-service:
    build:
      context: .
      dockerfile: ./gift-wishlist-service/Dockerfile
    container_name: gift-wishlist-service
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_URLS=http://+:5300
      - RabbitMq__HostName=rabbitmq
      - RabbitMq__UserName=guest
      - RabbitMq__Password=guest
      - RabbitMq__Port=5672
    ports:
      - "5300:5300"

  user-service:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    container_name: user-service
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_URLS=http://+:5400
      - RabbitMq__HostName=rabbitmq
      - RabbitMq__UserName=guest
      - RabbitMq__Password=guest
      - RabbitMq__Port=5672
    ports:
      - "5400:5400"

  wishera-app:
    build:
      context: ./WishlistApp
      dockerfile: Dockerfile
    container_name: wishera-app
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_URLS=http://+:5155
      - RabbitMq__HostName=rabbitmq
      - RabbitMq__UserName=guest
      - RabbitMq__Password=guest
      - RabbitMq__Port=5672
      - ChatServiceUrl=http://chat-service:5000
    ports:
      - "5155:5155"


